name: Elixir CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

defaults:
  run:
    working-directory: modermodemet
jobs:
  build:
  
    # services:
    #   postgres:
    #     image: postgres
    #     env:
    #       POSTGRES_PASSWORD: postgres
    #     options: >-
    #       --health-cmd pg_isready
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 5
    #     ports:
    #       - 5432:5432
          
    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@61e01a43a562a89bfc54c7f9a378ff67b03e4a21 # v1.16.0
      with:
        elixir-version: '1.15.5' 
        otp-version: '26.0'      
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    # - name: Run migrations
    #   env:
    #     MIX_ENV: test
    #     PGHOST: localhost
    #     POSTGRES_PORT: 5432
    #     POSTGRES_USER: postgres
    #     POSTGRES_PASSWORD: postgres
    #   run:
    #     mix ecto.drop
    #     mix ecto.create
    #     mix ecto.migrate
    - name: Run tests
      run:
        mix test
